name: Deployment Disabled

on:
  push:
    branches:
      - 'this-branch-does-not-exist'

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GitHub Pages deployment is disabled because Vercel is being used."
